[package]
name = "rs_tip_ty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
rs_tip_syntax = { path = "../rs_tip_syntax" }
